### ISSUE TITLE
Drop on Request Additional Information (general PAF suggestion)

### ISSUE THREAD

**Issue by 7CavIMO** [Jarvvski/CavTools#163] opened 2016-09-05 08:50 UTC
<h2>Problem</h2><br />Currently a DOR (Drop on Request) form does not contain related Department information, just the person: 

(Example: https://7cav.us/forums/drop-on-request.93/: 

[Drop on Request] - Nicolas Marcello

Proposed solution: Add department to the title/post?
Proposed solution can be applied to all PAF's (add company / department for all)<br /><hr><h2>Reason</h2><br />Better flow of information and quicker/easier handling of PAF's 

DOR would be: 
[Drop on Request] - [ RTC] - Nicolas Marcello

ELOA would be: 
[ELOA Request] - [B/2-7] - Binder.H<br><br>-Second Lieutenant Vermeulen.A

**Comment by MattTreck** [comment] 2016-10-12 18:05
This is how the system was intended to function, but isn't possible with the current plugin. When we write the new PAF this won't be an issue. Closing for now anyways as I'll remember this regardless as it's how I intended for it to work.

**Closed by MattTreck** 2016-10-12 18:05 UTC
Labels: Request
